### ISSUE TITLE
How to use fastText for out of sample words?

### ISSUE THREAD

**Issue by shgidi** [chaitaliSaini/gensim-data#26]
When downloading fastText with this method, we get a folder with a file in standard word2vec format, which can be loaded with
```model = KeyedVectors.load_word2vec_format(path, binary=False)```
But not with 
```from gensim.models import FastText```
```model = FastText.load_fasttext_format(path, binary=False)```

This disables the ability to get vectors for out-of-vocabulary words.
How can this be done correcly?

**Comment by menshikh-iv** [comment]
@shgidi 

Facebook distribute 2 type of files:
- `.vec` contains ONLY word-vectors (no ngrams here), can be loaded with `KeyedVectors.load_word2vec_format`
- `.bin` contains ngrams, can be loaded with `FastText.load_fasttext_format`


next time please ask in mailing list [mailing list](https://groups.google.com/forum/#!forum/gensim)

**Comment by piskvorky** [comment]
@menshikh-iv is this clear from our documentation?

I see people confused about these formats, how to load them and what can be done with them, all the time.

A clear, authoritative docs section would help us with support too (just point with hyperlink).

**Comment by menshikh-iv** [comment]
@piskvorky I agree this situation happens sometimes, it worth to make a tutorial.

**Comment by piskvorky** [comment]
A tutorial would be ideal, but a simple paragraph in the docs would go a long way. Can you add it?

**Comment by scottlittle** [comment]
This is not working for me with gensim 3.5, python 3.6, and a FB model:
```
from gensim.models import FastText
model_yelp = FastText.load_fasttext_format('yelp_review_full.bin')
```

I get:
`NotImplementedError: Supervised fastText models are not supported`

**Comment by menshikh-iv** [comment]
@scottlittle please read an exception again: we really don't support **supervised** fasttext models

**Comment by scottlittle** [comment]
@shgidi https://github.com/facebookresearch/fastText/tree/master/python worked for me.

**Comment by romass12** [comment]
What is meant by supervised fasttext models and how to train for unsupervised?

**Comment by menshikh-iv** [comment]
@romass12 

> supervised fasttext models

Exactly what [supervised learning](https://en.wikipedia.org/wiki/Supervised_learning) means. FB implementation have supervised-mode support (gensim - **only unsupervised**)

> how to train for unsupervised

Just read an [Gensim FastText documentation](https://radimrehurek.com/gensim/models/fasttext.html)
