### ISSUE TITLE
How to save the model downloaded from api locally?

### ISSUE THREAD

**Issue by livinglife2x** [chaitaliSaini/gensim-data#35]
I use
fasttext_model300 = api.load('fasttext-wiki-news-subwords-300')
to load the fasttext pretrained model. However everytime I run this code, I spend time on loading the model, is there a way to save this model locally and call it back?

**Comment by piskvorky** [comment]
Hi, yes there is, but please use the mailing list for questions: https://groups.google.com/forum/#!forum/gensim

Github is for technical bug reports. Thanks.
