### ISSUE TITLE
KeyError: "word '...' not in vocabulary" 20-newsgroups

### ISSUE THREAD

**Issue by gocen** [chaitaliSaini/gensim-data#41]
I want to use pre-trained 20-newsgroups model. My code is this:
`import gensim`
`from gensim.models import Word2Vec`
`import gensim.downloader as api`
`corpus = api.load('20-newsgroups')`
`model = Word2Vec(corpus)`
`print (model.similarity("jesus", "game"))`

It gives this error for any word

**Comment by piskvorky** [comment]
Duplicate of the (already resolved) https://github.com/RaRe-Technologies/gensim/issues/2856#issuecomment-643622686
