### ISSUE TITLE
How to download the model without using python

### ISSUE THREAD

**Issue by Welkin1027** [chaitaliSaini/gensim-data#46]
I am a Chinese who want to use gensim to test the similarity of two words. However, when I want to download the model by using gensim.downloader.load(""), I cannot connect to the website due to the lock of China, so I use a VPN to get access to the model. But it is very slow, it spend me almost 1 hour to download a file of 100MB, could you help me to solve it? For instance, if I can download the model from a website, and then I load the file locally.

**Comment by piskvorky** [comment]
The model files are hosted on Github. So if you cannot download from Github (or can download only slowly), there's not much we can do, sorry.
